name: Run Cypress using Wide Configuration
on:
  workflow_dispatch: # allow for manual execution

jobs:
  cypress-tests:
    name: Run Cypress
    runs-on: ubuntu-latest
    environment: dev

    strategy:
    matrix:
    browser: [chrome, firefox]
    spec:
    - './cypress/e2e/lena.cy.js'
    - './cypress/e2e/test.cy.js'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npx cypress run --spec "${{matrix.spec}}" --browser {{matrix.browser}}
